GET  http://localhost:3000/

###

POST http://localhost:3000/addPlant
Content-Type: application/json

{
    "name": "Sunflower", 
    "description": "Sunshine lover", 
    "care": "Loads of Sun", 
    "price": 5, 
    "image": "https://i.pinimg.com/originals/c5/65/39/c5653955525c8f24eee873156aca65f8.jpg"
}

###

DELETE http://localhost:3000/5e090cf364ee551faf1f1e76
