GET  http://localhost:3000/

###

POST http://localhost:3000/addPlant
Content-Type: application/json

{
    "name": "Rose", 
    "description": "Moms Roses", 
    "care": "Lots of Love", 
    "price": 100000, 
    "image": "https://target.scene7.com/is/image/Target/GUEST_be7e6313-15ac-4e1c-94b8-8af5595d6cb6?wid=488&hei=488&fmt=pjpeg"
}

###

DELETE http://localhost:3000/5e1605efe484964445ac6415

###

GET http://localhost:3000/5e179590cd54379121b4153d

###

PATCH http://localhost:3000/5e090eb1ac4b0d20dc9c712a
Content-Type: application/json

{
    "price": 15
}
